read_doc:
  description: >
    Read a text document from a file specified in the 
    path ```{original_cv}``` and return its content as a string.
  expected_output: >
    Return the content for the file read.
  agent: cv_adaptor

latex_summarizer:
  description: >
    The content received is a text document in latex format. Take this text, get rid of the commented latex
    , understand the remaining content, and reduce its content to contain only 3 pages approximately while preserving the original structure, semantics and syntax of the latex format.
  expected_output: >
    The latex document abbreviated and structured with proper formatting as text.
  agent: cv_adaptor

write_doc:
  description: >
    Write a latex-based document to a file specified in the path composed by the target dir ```{target_dir}``` and the filename that results from concatenating the prefix ```{filename_prefix}```, the current date and time, and the extension .tex.
  expected_output: >
    A confirmation that the file was written and where it is located.
  agent: cv_adaptor
