compile_doc:
  description: >
    Reads the tex file strictly specified in the path ```{document}``` and, without modifying it, compiles it.
  expected_output: >
    True if there are no errors, False otherwise.
  agent: latex_compiler
