compile_doc:
  description: >
    Compiles a latex-based document from a particular latex file specified in the tex file ```{document}```.
  expected_output: >
    True if there are no errors, False otherwise.
  agent: latex_compiler
