name: CV Compilation

roles:

  coder:
    name: Coding Agent
    description: |
      Read a the content of a latex file and summarize it respecting the latex structure and format of the document.
    agent_system_message: |
      You are an experienced programmer with strong Python skills and superior knowledge of latex. In addition, you
      are an expert in condensing information without loosing the original structure and semantics of the document.

    tasks:
      read_doc:
        name: Read doc content
        description: |
          Write a python program that reads a text document from a file specified in the 
          path ```{document}```, executes it returns its content as a string.
        expected_output: |
          Return the output of the program execution which represents a latex document as text.

      latex_summarizer:
        name: Summarizes the latex document passed.
        description: |
          The returned by the program is a latex-based document. Take this text, understand it, and 
          reduce its content to contain only 3 pages approximately while preserving the original 
          structure, semantics and syntax of the latex format.
        expected_output: |
          The latex document abbreviated and structured with proper formatting as text.

      save_doc:
        name: Save Latex doc content
        description: |
          Saves a latex-based document to a file named "dummy.tex".
        expected_output: |
          The saved document.


  latex_compiler:
    name: Latex Compilation
    description: You are an expert in compiling documents based on latex format
    agent_system_message: |
      You are an expert in compiling documents based on latex format. 
      You should only compile a latex document if it is in the correct format.

    tasks:

      compile_doc:
        name: Compile Latex
        description: |
          Compiles a latex-based document from a particular latex file specified in the tex file ```{document}```..
        expected_output: |
          True if there are no errors, False otherwise.
          
